### ISSUE TITLE
Changement de mot de passe

### ISSUE THREAD

**Issue by jac110** [ClaudeStabile/GREEN_SPIDER#16]
Bravo Claude pour le développement continu de GS OS !

J'ai téléchargé la dernière version de l'OS depuis une ancienne clef. et cherche à changer le mot de passe du profil de base. Je reçois le message d'erreur suivant:

_Le mot de passe ne passe pas la vérification dans le dictionnaire - erreur lors du chargement du dictionnaire_

J'utilise le 'Gestionnaire d'utilisateurs' depuis 'Configuration du système' dans le lanceur Cairo-Dock du bas.

Merci d'avance,
Jacques

**Comment by ClaudeStabile** [comment]
Merci,

je check ceci

++

**Comment by ClaudeStabile** [comment]
Work around :+1: 

Ouvrir un terminal et tapez passwd

**Comment by ClaudeStabile** [comment]
Pour corriger le prob :
sudo apt-get install --reinstall cracklib-runtime 
Correctif inclu dans la nouvelle version 5.26

**Comment by ClaudeStabile** [comment]
Issue Fixed in latest release 5.26
Prob corrigé dans la nouvelle version 5.26
