### ISSUE TITLE
Création d'un script pour MacOS équivalent à CreateFSKey.sh

### ISSUE THREAD

**Issue by ClaudeStabile** [ClaudeStabile/GREEN_SPIDER#2]
Avis aux contributeurs, Si quelqu'un peut proposer un script pour Mac ça serai une grande avancée

Il s'agit de pouvoir executer l'équivalent de la commande Ubuntu Linux dans un terminal MacOS
curl -N -s https://www.free-solutions.ch/GREEN_SPIDER/4.0/GREEN_SPIDER_5.0.3.dd.gz | gunzip -c | pv -B32M > $DEVUSB

curl peut être remplacé par wget et pv par dd

**Comment by abu921** [comment]
Je vous propose [un script pour créer la clé GREEN SPIDER depuis un mac](https://github.com/ClaudeStabile/GREEN_SPIDER/blob/main/CreateFSKey-formac.sh).
Le script a été réalisé et testé depuis un macbook pro en 10.11.6 sans port USB3.

Principe de fonctionnement.

- Brancher votre clé USB 
- Ouvrir un terminal et se placer dans le répertoire ou vous avez préalablement téléchargé le script de création
- Au lancement, le script cherche la distribution dans le même répertoire que le script. S'il ne la trouve pas, il la télécharge.(Attention 9Go d'espace)

Une fois le téléchargement terminé, il liste les disques.
- Choisir votre clé USB parmi la liste. Attention le disque sera entièrement formaté, toutes les données seront effacées.
- Confirmer votre choix avec Y
- Patienter pendant la création de votre clé. La création prendra 25min minimum sur port USB3 avec clé Sandisk ultrafit USB 3.1 32GB. Ce délai peut augmenter si USB2 ou clé USB de qualité moindre.
(Personnellement : 38min sur clé Sandisk sur port USB2)

Capture d'écran de l'execution du script :
![Capture d’écran 2020-10-12 à 16 02 48](https://user-images.githubusercontent.com/55857398/95755384-a35ec900-0ca4-11eb-980a-eec4618dc392.png)

**Comment by abu921** [comment]
Comme mentionné dans les sources, une partie du script provient de https://stackoverflow.com/questions/15274269/bash-user-drive-selection, plus particulièrement de l'utilisateur https://stackoverflow.com/users/1126841/chepner

**Comment by ClaudeStabile** [comment]
Excellentissime !

Donc on sait maintenant passer de Mac à Free-Solutions OS sur Mac aussi

Merci Beaucoup pour cette contrib

**Comment by ClaudeStabile** [comment]
Je recommande l'utilisation de Etcher qui fait parfaitement le job sur MacOS C'est aussi un projet Libre auquel je recommande de contribuer https://github.com/balena-io/etcher
