### ISSUE TITLE
pbm with script for update

### ISSUE THREAD

**Issue by andre0ani** [ClaudeStabile/GREEN_SPIDER#21]
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

The key is not reconize correctly.

sudo fdisk -l /dev/sdb
Disque /dev/sdb : 28,65 GiB, 30765219840 octets, 60088320 secteurs
Modèle de disque : Ultra Fit       
Unités : secteur de 1 × 512 = 512 octets
Taille de secteur (logique / physique) : 512 octets / 512 octets
taille d'E/S (minimale / optimale) : 512 octets / 512 octets
Type d'étiquette de disque : gpt
Identifiant de disque : 743D87D0-2162-4729-AA2E-29981C7F5729

Périphérique    Début      Fin Secteurs Taille Type
/dev/sdb1    60085937 60088286     2350   1,1M Données de base Microsoft
/dev/sdb2        2048     4095     2048     1M Amorçage BIOS
/dev/sdb3        4096   503807   499712   244M Système EFI
/dev/sdb4      503808  5705727  5201920   2,5G Système de fichiers Linux
/dev/sdb5     5705728 47798271 42092544  20,1G Système de fichiers Linux
/dev/sdb6    47798272 60084223 12285952   5,9G Partition d'échange Linux

**Comment by ClaudeStabile** [comment]
@andre0ani : Si tu peux réessayer avec la nouvelle version ça doit faire, met à jour le script à partir de github et refait à l occaz

Merci d avance pour tester 

++
Je close l'issue quand tu me dit que c est bon

**Comment by andre0ani** [comment]
Ce programme va créer une clé USB de démarrage d'un ordimateur
Après démarrage de l'ordinateur depuis cette clé USB, un environnement
        graphique sous Linux est mis à la disposition de l'utilisateur
!!! N'introduisez la clé USB que lorsque le programme le demande !!!
Merci de suivre les autres instructions à l'écran svp
Ce programme n'est testé que sur Debian, Ubuntu et dérivés (Kubuntu, etc)
Réessayez ultérieurement svp


cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

**Comment by ghost** [comment]
Bonjour,
Le programme est corrigé. Voulez-vous essayer à nouveau, et m'informer du résultat ?
Merci

**Comment by andre0ani** [comment]
Ca fonctionne, merci ;-)

**Comment by ClaudeStabile** [comment]
Je close l'issue, 

Merci @GITaccountforDOg for update + merci @andre0ani for testing :)
