### ISSUE TITLE
Password session

### ISSUE THREAD

**Issue by jinformatique** [ClaudeStabile/GREEN_SPIDER#26]
Où peut-on trouver le mot de passe pour ouvrir la session ?
Pourras-tu le rajouter dans le readme ?
Un grand merci.

**Comment by ClaudeStabile** [comment]
Hello,

C'est déjà dans le README, il y a un lien sur https://www.free-solutions.ch/clearspace/servlet/JiveServlet/downloadBody/3815-102-2-4840/LettreFS_avec_clef.pdf et le pass est dans ce document. Password à changer bien évidement si vous utilisez, ça va de soi

++
