### ISSUE TITLE
Si quelqu'un peut proposer un script pour PC Windows10 équivalent à CreateFSKey.sh

### ISSUE THREAD

**Issue by ClaudeStabile** [ClaudeStabile/GREEN_SPIDER#3]
Avis aux contributeurs, Si quelqu'un peut proposer un script pour PC Windows10 ça serai une grande avancée
Il s'agit de pouvoir executer une commande équivalente à la commande Linux Ubuntu 

curl -N -s https://www.free-solutions.ch/GREEN_SPIDER/4.0/GREEN_SPIDER_5.0.3.dd.gz | gunzip -c | pv -B32M > $DEVUSB

curl peut être remplacé par wget et pv par dd

**Comment by abu921** [comment]
Voici une technique de création de la clé GREEN SPIDER sur environnement Microsoft (W7, W10, etc).
Télécharger l'utilitaire Rufus. La version portable est suffisante : https://github.com/pbatard/rufus/releases/download/v3.11/rufus-3.11p.exe

Télécharger la distribution Green SPIDER sur votre pc ( nécessite environ 9Go de stockage) : [https://www.free-solutions.ch/GREEN_SPIDER/4.0/GREEN_SPIDER_5.0.3.dd.gz |](https://www.free-solutions.ch/GREEN_SPIDER/4.0/GREEN_SPIDER_5.0.3.dd.gz)

Brancher votre clé USB de préférence sur un port USB3, elle va être formatée, toutes les données seront supprimées et la distribution Green Spider sera installée.
Il est recommandé d'utiliser une clé Sandisk ultrafit USB 3.1 32GB minimum pour des performances optimales.

Executer Rufus par un simple double clic sur le fichier téléchargé précédemment.

Dans Rufus : 
-> Périphérique doit pointer sur votre clé
-> Cliquer sur le bouton "Sélection" et sélectionner le fichier de la distribution Green Spider : GREEN_SPIDER_5.0.3.dd.gz
-> Cliquer sur le bouton "ouvrir" pour valider
-> Cliquer sur le bouton "Démarrer" pour lancer l'opération
-> Patienter jusqu'à la fin de l'opération. Un message vous indique la fin de l'opération

![GreenSpider - Capture - Rufus](https://user-images.githubusercontent.com/55857398/95728067-55819b00-0c7b-11eb-84a0-73fca56816aa.PNG)

Une fois l'opération terminée, il ne vous reste plus qu'à rebooter votre poste de travail et booter directement sur la clé pour profiter pleinement des performances de votre matériel.

Pour le démarrage depuis le port USB et pour ouvrir votre première session, une aide est disponible ici : http://www.free-solutions.ch/clearspace/servlet/JiveServlet/previewBody/4537-102-1-7267/LettreFS_avec_clef.pdf;jsessionid=4EDE2DEF3091E9A6F44F424C57DF35A2

**Comment by ClaudeStabile** [comment]
Bravo, 

Merci pour la doc. Permet de passer de Win10 à Free-Solutions OS directement :) Et tout est dans la clé. Merci d'utiliser des clés Sandisk ultrafit 32GB pour des performances optimales

Merci pour cette belle contrib :)

**Comment by ClaudeStabile** [comment]
On sait faire le job avec Etcher directement sur Mac et PC windows https://www.balena.io/etcher/ . Je recommande d'utiliser ce package ou d'y contribuer https://github.com/balena-io/etcher
